unstable_features = true
version = "Two"

# Imports
imports_granularity = "Crate"
group_imports = "StdExternalCrate"

# Consistency
newline_style = "Unix"

# Comments
wrap_comments = true
format_code_in_doc_comments = true
